# Generated by Django 4.0.3 on 2022-03-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Таблица',
            },
        ),
    ]
